### PR TITLE
Opaque arrow render fix

### PR DESCRIPTION
**Pull request by YannickMG**
Fixes GTNewHorizons/GT-New-Horizons-Modpack#8349 about TCNodeTracker sometimes having a black opaque square around it's pointer arrow when another mod is drawing on the screen before it and disables GL_BLEND, which is needed to draw the pointer arrow with transparency.

I'm not sure whether the right fix is instead to stop other mods from disabling GL_BLEND. From some quick research it appears that there is a performance cost to keeping GL_BLEND enabled when it is not needed, and likewise there is a (hopefully lesser) cost to enabling and disabling it regularly. If someone knows any better than I what the right thing to do here is I'd love to hear it. Either way this works.

### Before
tc-node-tracker-broken

### After
tc-node-tracker-fixed

### CODE REVIEW

**Comment by bombcar** [comment]
I suspect if there is a performance hit leaving it on that optifine would do some trickery around it. Does your fix do anything different with/without optifine?

**Comment by YannickMG** [comment]
> I suspect if there is a performance hit leaving it on that optifine would do some trickery around it. Does your fix do anything different with/without optifine?

Good question, works fine with or without. This being said I can't imagine Optifine would insert itself in the middle of a render function call to disrupt it or we'd see graphical glitches all the time.

**Comment by ElNounch** [comment]
Since you identified the troublemaker (AdventureBackpack), why not fixing it there ?
Might jerk other stuff too...

**Comment by boubou19** [comment]
When someone identifies an issue with a mod setting the OGL engine in an incorrect state, it's our duty to fix it in the mod causing it, because who knows what kind of weird rendering bug it will solve?

**Comment by YannickMG** [comment]
Well that's exactly what I'm asking about. Is mod A at fault for turning off GL_BLEND which is a performance improvement (in theory) or is another mod at fault for expecting GL_BLEND to be already turned on?

In my mind a mod which renders GL stuff without setting up all the flags they need is the one at fault.

**Comment by YannickMG** [comment]
> Since you identified the troublemaker (AdventureBackpack), why not fixing it there ? Might jerk other stuff too...

Also there's nothing special about AdventureBackpack, any other mod, even those we don't have control over, might choose to disable GL_BLEND. I figured hardening TCNodeTracker against that was the way to go.

**Comment by boubou19** [comment]
i'm not that much into OGL engine stuff, but from my experience, every mod makes the assumption that other mods left the OGL engine in a correct state. If they were all setting the OGL engine in a known state before doing stuff, we would have no issue at all. It's great that you hardened TCNodeTracker, but now that we know that advanced backpacks might be doing bad stuff, would be nice that someone someday do a fix for it. But at least it is known now thanks for the catch.

**Comment by YannickMG** [comment]
Alright, in that case I'll close this PR and GTNewHorizons/GT-New-Horizons-Modpack#7903 should be closed as out of scope unless we bring https://www.curseforge.com/minecraft/mc-mods/thaumic-utilities into the pack, as it is caused by AdventureBackpack2 expecting GL_BLEND to be on during status drawing just like TCNodeTracker is doing now. (Yeah they're inconsistent)

**Comment by bombcar** [comment]
Personally I like the hardening unless it results in a worse state than before. OpenGL are so hard to track down. 

Does it make sense to see what it “usually” is and then only fix it if wrong (and print a “warn” maybe? Risk of a2 - maybe the first time we have to “fix” we report a warning but not afterwards)

**Comment by YannickMG** [comment]
> Personally I like the hardening unless it results in a worse state than before. OpenGL are so hard to track down.
> 
> Does it make sense to see what it “usually” is and then only fix it if wrong (and print a “warn” maybe? Risk of a2 - maybe the first time we have to “fix” we report a warning but not afterwards)

Hardening only in this case means setting GL_BLEND to on before you use it, and then not disabling it.

The logging sounds like a code-base wide project to audit every mod that uses GL11 calls to render, but it might help gain some insights into what the proper way to handle this is.

**Comment by bombcar** [comment]
At that point you log in OpenGL itself (which results in acres of a2 lol)

**Comment by ElNounch** [comment]
> Well that's exactly what I'm asking about. Is mod A at fault for turning off GL_BLEND which is a performance improvement (in theory) or is another mod at fault for expecting GL_BLEND to be already turned on?
> 
> In my mind a mod which renders GL stuff without setting up all the flags they need is the one at fault.

I didn't meant your PR wasn't useful. : in my mind, they both are at fault. ;)

AdventureBackpack shouldn't let OpenGL states spill out, TCNodeTracker shouldn't be sensible to it.

I would glPushAttrib(), then force values , draw, an glPopAttrib at end.

My two cents...

**Comment by YannickMG** [comment]
Right I'll need to take a good look at what you did with AdventureBackpack2 as I'm a complete OpenGL beginner.

**Pull request closed without merging**
